package com.pdfpocket.lite.core

enum class AppError {
    FILE_NOT_FOUND, INVALID_URI, PERMISSION_DENIED, CORRUPTED_PDF, PASSWORD_REQUIRED,
    WRONG_PASSWORD, UNSUPPORTED_FORMAT, NOT_ENOUGH_STORAGE, OUT_OF_MEMORY,
    CANCELLED, SAVE_FAILED, SHARE_FAILED, OCR_FAILED, CAMERA_FAILED, UNKNOWN
}
